[variables]
NODE_ENV = "production"

[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmd = "pnpm install --frozen-lockfile --prod"

[phases.build] 
cmd = "pnpm run build"

[start]
cmd = "pnpm start"