# nixpacks.toml - Railway configuration
[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build] 
cmds = [
  "npx prisma generate",
  "pnpm run compile"
]

[start]
cmd = "pnpm run railway:start"

[variables]
NODE_ENV = "production"