[build]
builder = "NIXPACKS"

[build.environment]
NPM_CONFIG_PRODUCTION = "false"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[networking]
internal = false
externalPort = 4000